name: Daily HOT Coin Analysis

on:
  schedule:
    - cron: '0 1 * * *'  # 오전 10시 KST
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Decode firebase_key.json from base64
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > firebase_key.json

      - name: Run analysis script
        run: python daily_analysis2.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase_key.json
