name: Daily BTC Analysis

on:
  schedule:
    - cron: '0 1 * * *'  # 매일 오전 10시(KST)
  workflow_dispatch:     # 수동 실행도 가능

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create Firebase service account key
        run: echo "$GCP_CREDENTIALS_JSON" > bitway-b9001-firebase-adminsdk-fbsvc-3db339356a.json
        env:
          GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Run analysis script
        run: python daily_analysis.py
